// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    datum/atom/movable/mob.cc
#include "donk/api/datum/atom/movable/mob.h"

#include "donk/api/datum/atom/movable.h"
#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"
#include "donk/core/vars.h"

namespace donk::api::datum::atom::movable::mob {
mob_coretype::mob_coretype(donk::path_t path)
    : donk::iota_t(path),
      donk::api::datum::atom::movable::movable_coretype(path) {
  InternalCoreRegister();
}

donk::running_proc Login(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/datum/atom/movable/mob/proc/Login");
}

donk::running_proc Logout(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/datum/atom/movable/mob/proc/Logout");
}

void mob_coretype::InternalCoreRegister() {
  RegisterProc("Login", donk::api::datum::atom::movable::mob::Login);
  RegisterProc("Logout", donk::api::datum::atom::movable::mob::Logout);
  RegisterVar("ckey");
  RegisterVar("client");
  RegisterVar("group");
  RegisterVar("key");
  donk::var_t donk_value_var__layer = 4;
  RegisterVar("layer", donk_value_var__layer);
  donk::var_t donk_value_var__parent_type =
      donk::prefab_t("/datum/atom/movable");
  RegisterVar("parent_type", donk_value_var__parent_type);
  RegisterVar("see_in_dark");
  RegisterVar("see_infrared");
  RegisterVar("see_invisible");
  RegisterVar("sight");
}

}  // namespace donk::api::datum::atom::movable::mob