// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    datum/atom/movable/obj.cc
#include "donk/api/datum/atom/movable/obj.h"

#include "donk/api/datum/atom/movable.h"
#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"
#include "donk/core/vars.h"

namespace donk::api::datum::atom::movable::obj {
obj_coretype::obj_coretype(donk::path_t path)
    : donk::iota_t(path),
      donk::api::datum::atom::movable::movable_coretype(path) {
  InternalCoreRegister();
}

void obj_coretype::InternalCoreRegister() {
  donk::var_t donk_value_var__layer = 3;
  RegisterVar("layer", donk_value_var__layer);
  donk::var_t donk_value_var__parent_type =
      donk::prefab_t("/datum/atom/movable");
  RegisterVar("parent_type", donk_value_var__parent_type);
}

}  // namespace donk::api::datum::atom::movable::obj