// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    database/query.h

#ifndef __DONK_API_DATABASE_QUERY_H__
#define __DONK_API_DATABASE_QUERY_H__

#include "cppcoro/generator.hpp"
#include "donk/api/database.h"
#include "donk/core/procs.h"

namespace donk::api::database::query {

class query_coretype : public donk::api::database::database_coretype {
 public:
  ~query_coretype() {}
  void InternalCoreRegister() override;

  query_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Add(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Close(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Columns(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Error(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ErrorMsg(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Execute(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc GetColumn(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc GetRowData(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc NextRow(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Reset(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc RowsAffected(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);

}  // namespace donk::api::database::query

#endif  // __DONK_API_DATABASE_QUERY_H__
