// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    datum/atom/area.cc
#include "donk/api/datum/atom/area.h"

#include "donk/api/datum/atom.h"
#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"
#include "donk/core/vars.h"

namespace donk::api::datum::atom::area {
area_coretype::area_coretype(donk::path_t path)
    : donk::iota_t(path), donk::api::datum::atom::atom_coretype(path) {
  InternalCoreRegister();
}

void area_coretype::InternalCoreRegister() {
  donk::var_t donk_value_var__layer = 1;
  RegisterVar("layer", donk_value_var__layer);
  donk::var_t donk_value_var__luminosity = 1;
  RegisterVar("luminosity", donk_value_var__luminosity);
  donk::var_t donk_value_var__parent_type = donk::prefab_t("/datum/atom");
  RegisterVar("parent_type", donk_value_var__parent_type);
}

}  // namespace donk::api::datum::atom::area