// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    datum/atom/area.h

#ifndef __DONK_API_DATUM_ATOM_AREA_H__
#define __DONK_API_DATUM_ATOM_AREA_H__

#include "donk/api/datum/atom.h"
#include "donk/core/procs.h"

namespace donk::api::datum::atom::area {

class area_coretype : public donk::api::datum::atom::atom_coretype {
 public:
  ~area_coretype() {}
  void InternalCoreRegister() override;

  area_coretype(donk::path_t path);

  friend class donk::iota_t;
};

}  // namespace donk::api::datum::atom::area

#endif  // __DONK_API_DATUM_ATOM_AREA_H__
