// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    datum/atom/movable.h

#ifndef __DONK_API_DATUM_ATOM_MOVABLE_H__
#define __DONK_API_DATUM_ATOM_MOVABLE_H__

#include "cppcoro/generator.hpp"
#include "donk/api/datum/atom.h"
#include "donk/core/procs.h"

namespace donk::api::datum::atom::movable {

class movable_coretype : public donk::api::datum::atom::atom_coretype {
 public:
  ~movable_coretype() {}
  void InternalCoreRegister() override;

  movable_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Bump(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Move(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::datum::atom::movable

#endif  // __DONK_API_DATUM_ATOM_MOVABLE_H__
