// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    datum/atom/turf.h

#ifndef __DONK_API_DATUM_ATOM_TURF_H__
#define __DONK_API_DATUM_ATOM_TURF_H__

#include "donk/api/datum/atom.h"
#include "donk/core/procs.h"

namespace donk::api::datum::atom::turf {

class turf_coretype : public donk::api::datum::atom::atom_coretype {
 public:
  ~turf_coretype() {}
  void InternalCoreRegister() override;

  turf_coretype(donk::path_t path);

  friend class donk::iota_t;
};

}  // namespace donk::api::datum::atom::turf

#endif  // __DONK_API_DATUM_ATOM_TURF_H__
