// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    datum/atom.h

#ifndef __DONK_API_DATUM_ATOM_H__
#define __DONK_API_DATUM_ATOM_H__

#include "cppcoro/generator.hpp"
#include "donk/api/datum.h"
#include "donk/core/procs.h"

namespace donk::api::datum::atom {

class atom_coretype : public donk::api::datum::datum_coretype {
 public:
  ~atom_coretype() {}
  void InternalCoreRegister() override;

  atom_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Click(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Cross(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Crossed(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc DblClick(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Enter(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Entered(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Exit(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Exited(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseDown(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseDrag(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseDrop(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseEntered(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc MouseExited(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc MouseMove(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseUp(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseWheel(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Stat(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Uncross(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Uncrossed(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::datum::atom

#endif  // __DONK_API_DATUM_ATOM_H__
