// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    client.h

#ifndef __DONK_API_CLIENT_H__
#define __DONK_API_CLIENT_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::client {

class client_coretype : public virtual donk::iota_t {
 public:
  ~client_coretype() {}
  void InternalCoreRegister() override;

  client_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc AllowUpload(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc Center(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc CheckPassport(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc Click(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Command(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc DblClick(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Del(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc East(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Export(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Import(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc IsByondMember(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc MeasureText(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc MouseDown(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseDrag(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseDrop(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseEntered(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc MouseExited(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc MouseMove(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseUp(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MouseWheel(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Move(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc North(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Northeast(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Northwest(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc SendPage(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc SoundQuery(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc South(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Southeast(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Southwest(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Stat(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Topic(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc West(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::client

#endif  // __DONK_API_CLIENT_H__
