// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    database.h

#ifndef __DONK_API_DATABASE_H__
#define __DONK_API_DATABASE_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::database {

class database_coretype : public virtual donk::iota_t {
 public:
  ~database_coretype() {}
  void InternalCoreRegister() override;

  database_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Close(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Error(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ErrorMsg(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Open(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::database

#endif  // __DONK_API_DATABASE_H__
