// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    datum.h

#ifndef __DONK_API_DATUM_H__
#define __DONK_API_DATUM_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::datum {

class datum_coretype : public virtual donk::iota_t {
 public:
  ~datum_coretype() {}
  void InternalCoreRegister() override;

  datum_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Del(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Read(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Topic(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Write(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::datum

#endif  // __DONK_API_DATUM_H__
