// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    exception.h

#ifndef __DONK_API_EXCEPTION_H__
#define __DONK_API_EXCEPTION_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::exception {

class exception_coretype : public virtual donk::iota_t {
 public:
  ~exception_coretype() {}
  void InternalCoreRegister() override;

  exception_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::exception

#endif  // __DONK_API_EXCEPTION_H__
