// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    generator.h

#ifndef __DONK_API_GENERATOR_H__
#define __DONK_API_GENERATOR_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::generator {

class generator_coretype : public virtual donk::iota_t {
 public:
  ~generator_coretype() {}
  void InternalCoreRegister() override;

  generator_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Rand(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Turn(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::generator

#endif  // __DONK_API_GENERATOR_H__
