// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    icon.h

#ifndef __DONK_API_ICON_H__
#define __DONK_API_ICON_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::icon {

class icon_coretype : public virtual donk::iota_t {
 public:
  ~icon_coretype() {}
  void InternalCoreRegister() override;

  icon_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Blend(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Crop(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc DrawBox(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Flip(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc GetPixel(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Height(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc IconStates(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Insert(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc MapColors(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Scale(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc SetIntensity(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc Shift(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc SwapColor(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Turn(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Width(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::icon

#endif  // __DONK_API_ICON_H__
