// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    image.h

#ifndef __DONK_API_IMAGE_H__
#define __DONK_API_IMAGE_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::image {

class image_coretype : public virtual donk::iota_t {
 public:
  ~image_coretype() {}
  void InternalCoreRegister() override;

  image_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::image

#endif  // __DONK_API_IMAGE_H__
