// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    image.cc
#include "donk/api/image.h"

#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"

namespace donk::api::image {
image_coretype::image_coretype(donk::path_t path) : donk::iota_t(path) {
  InternalCoreRegister();
}

donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/image/proc/New");
}

void image_coretype::InternalCoreRegister() {
  RegisterProc("New", donk::api::image::New);
  RegisterVar("alpha");
  RegisterVar("animate_movement");
  RegisterVar("appearance");
  RegisterVar("appearance_flags");
  RegisterVar("blend_mode");
  RegisterVar("color");
  RegisterVar("density");
  RegisterVar("desc");
  RegisterVar("dir");
  RegisterVar("filters");
  RegisterVar("gender");
  RegisterVar("icon");
  RegisterVar("icon_state");
  RegisterVar("invisibility");
  donk::var_t donk_value_var__layer = 5;
  RegisterVar("layer", donk_value_var__layer);
  RegisterVar("loc");
  RegisterVar("luminosity");
  RegisterVar("maptext");
  RegisterVar("maptext_height");
  RegisterVar("maptext_width");
  RegisterVar("maptext_x");
  RegisterVar("maptext_y");
  RegisterVar("mouse_drag_pointer");
  RegisterVar("mouse_drop_pointer");
  RegisterVar("mouse_drop_zone");
  RegisterVar("mouse_opacity");
  RegisterVar("mouse_over_pointer");
  RegisterVar("name");
  RegisterVar("opacity");
  RegisterVar("overlays");
  RegisterVar("override");
  RegisterVar("pixel_w");
  RegisterVar("pixel_x");
  RegisterVar("pixel_y");
  RegisterVar("pixel_z");
  RegisterVar("plane");
  RegisterVar("render_source");
  RegisterVar("render_target");
  RegisterVar("screen_loc");
  RegisterVar("suffix");
  RegisterVar("text");
  RegisterVar("transform");
  RegisterVar("underlays");
  RegisterVar("verbs");
  RegisterVar("vis_contents");
  RegisterVar("vis_flags");
  RegisterVar("x");
  RegisterVar("y");
  RegisterVar("z");
}

}  // namespace donk::api::image