// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    list.cc
#include "donk/api/list.h"

#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"

namespace donk::api::list {
list_coretype::list_coretype(donk::path_t path) : donk::iota_t(path) {
  InternalCoreRegister();
}

donk::running_proc Add(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Add");
}

donk::running_proc Copy(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Copy");
}

donk::running_proc Cut(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Cut");
}

donk::running_proc Find(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Find");
}

donk::running_proc Insert(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Insert");
}

donk::running_proc Join(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Join");
}

donk::running_proc Remove(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Remove");
}

donk::running_proc Splice(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Splice");
}

donk::running_proc Swap(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/list/proc/Swap");
}

void list_coretype::InternalCoreRegister() {
  RegisterProc("Add", donk::api::list::Add);
  RegisterProc("Copy", donk::api::list::Copy);
  RegisterProc("Cut", donk::api::list::Cut);
  RegisterProc("Find", donk::api::list::Find);
  RegisterProc("Insert", donk::api::list::Insert);
  RegisterProc("Join", donk::api::list::Join);
  RegisterProc("Remove", donk::api::list::Remove);
  RegisterProc("Splice", donk::api::list::Splice);
  RegisterProc("Swap", donk::api::list::Swap);
  RegisterVar("len");
  RegisterVar("parent_type");
  RegisterVar("tag");
  RegisterVar("type");
}

}  // namespace donk::api::list