// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    matrix.h

#ifndef __DONK_API_MATRIX_H__
#define __DONK_API_MATRIX_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::matrix {

class matrix_coretype : public virtual donk::iota_t {
 public:
  ~matrix_coretype() {}
  void InternalCoreRegister() override;

  matrix_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Add(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Interpolate(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc Invert(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Multiply(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Scale(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Subtract(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Translate(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Turn(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::matrix

#endif  // __DONK_API_MATRIX_H__
