// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    mutable_appearance.cc
#include "donk/api/mutable_appearance.h"

#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"
#include "donk/core/vars.h"

namespace donk::api::mutable_appearance {
mutable_appearance_coretype::mutable_appearance_coretype(donk::path_t path)
    : donk::iota_t(path) {
  InternalCoreRegister();
}

void mutable_appearance_coretype::InternalCoreRegister() {
  RegisterVar("opacity");
  donk::var_t donk_value_var__parent_type = donk::prefab_t("/image");
  RegisterVar("parent_type", donk_value_var__parent_type);
}

}  // namespace donk::api::mutable_appearance