// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    mutable_appearance.h

#ifndef __DONK_API_MUTABLE_APPEARANCE_H__
#define __DONK_API_MUTABLE_APPEARANCE_H__

#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::mutable_appearance {

class mutable_appearance_coretype : public virtual donk::iota_t {
 public:
  ~mutable_appearance_coretype() {}
  void InternalCoreRegister() override;

  mutable_appearance_coretype(donk::path_t path);

  friend class donk::iota_t;
};

}  // namespace donk::api::mutable_appearance

#endif  // __DONK_API_MUTABLE_APPEARANCE_H__
