// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    particles.cc
#include "donk/api/particles.h"

#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"

namespace donk::api::particles {
particles_coretype::particles_coretype(donk::path_t path) : donk::iota_t(path) {
  InternalCoreRegister();
}

void particles_coretype::InternalCoreRegister() {
  RegisterVar("bound1");
  RegisterVar("bound2");
  RegisterVar("color");
  RegisterVar("color_change");
  RegisterVar("count");
  RegisterVar("drift");
  RegisterVar("fade");
  RegisterVar("friction");
  RegisterVar("gradient");
  RegisterVar("gravity");
  RegisterVar("height");
  RegisterVar("icon");
  RegisterVar("icon_state");
  RegisterVar("lifespan");
  RegisterVar("position");
  RegisterVar("rotation");
  RegisterVar("scale");
  RegisterVar("spawning");
  RegisterVar("spin");
  RegisterVar("transform");
  RegisterVar("velocity");
  RegisterVar("width");
}

}  // namespace donk::api::particles