// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    particles.h

#ifndef __DONK_API_PARTICLES_H__
#define __DONK_API_PARTICLES_H__

#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::particles {

class particles_coretype : public virtual donk::iota_t {
 public:
  ~particles_coretype() {}
  void InternalCoreRegister() override;

  particles_coretype(donk::path_t path);

  friend class donk::iota_t;
};

}  // namespace donk::api::particles

#endif  // __DONK_API_PARTICLES_H__
