// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    regex.h

#ifndef __DONK_API_REGEX_H__
#define __DONK_API_REGEX_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::regex {

class regex_coretype : public virtual donk::iota_t {
 public:
  ~regex_coretype() {}
  void InternalCoreRegister() override;

  regex_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Find(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Find_char(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Replace(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Replace_char(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);

}  // namespace donk::api::regex

#endif  // __DONK_API_REGEX_H__
