// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    root.h

#ifndef __DONK_API_ROOT_H__
#define __DONK_API_ROOT_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api {

donk::running_proc CRASH(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc REGEX_QUOTE(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc REGEX_QUOTE_REPLACEMENT(donk::proc_ctxt_t& ctxt,
                                           donk::proc_args_t& args);
donk::running_proc _dm_db_close(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc _dm_db_columns(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc _dm_db_connect(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc _dm_db_error_msg(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc _dm_db_execute(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc _dm_db_is_connected(donk::proc_ctxt_t& ctxt,
                                       donk::proc_args_t& args);
donk::running_proc _dm_db_new_con(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc _dm_db_new_query(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc _dm_db_next_row(donk::proc_ctxt_t& ctxt,
                                   donk::proc_args_t& args);
donk::running_proc _dm_db_quote(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc _dm_db_row_count(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc _dm_db_rows_affected(donk::proc_ctxt_t& ctxt,
                                        donk::proc_args_t& args);
donk::running_proc abs(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc addtext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc alert(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc animate(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc arccos(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc arcsin(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc arctan(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc arglist(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ascii2text(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc block(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc bounds(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc bounds_dist(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc browse(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc browse_rsc(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ckey(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ckeyEx(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc clamp(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc cmptext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc cmptextEx(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc copytext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc copytext_char(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc cos(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc fcopy(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc fcopy_rsc(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc fdel(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc fexists(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc file(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc file2text(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc filter(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc findlasttext(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc findlasttextEx(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc findlasttextEx_char(donk::proc_ctxt_t& ctxt,
                                       donk::proc_args_t& args);
donk::running_proc findlasttext_char(donk::proc_ctxt_t& ctxt,
                                     donk::proc_args_t& args);
donk::running_proc findtext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc findtextEx(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc findtextEx_char(donk::proc_ctxt_t& ctxt,
                                   donk::proc_args_t& args);
donk::running_proc findtext_char(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc flick(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc flist(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ftp(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc generator(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc get_dir(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc get_dist(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc get_step(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc get_step_away(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc get_step_rand(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc get_step_to(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc get_step_towards(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc gradient(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc hascall(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc hearers(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc html_decode(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc html_encode(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc icon_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc icon_states(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc image_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc initial(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc input(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isarea(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isfile(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isicon(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc islist(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isloc(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ismob(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ismovable(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isnull(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isnum(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isobj(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ispath(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc issaved(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc istext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc isturf(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc istype(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc jointext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc json_decode(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc json_encode(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc length(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc length_char(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc lentext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc link(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc list_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc list2params(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc load_resource(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc locate(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc log(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc lowertext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc matrix_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc max(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc md5(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc min(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc missile(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc newlist(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc nonspantext(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc nonspantext_char(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc num2text(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc obounds(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ohearers(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc orange(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc output(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc oview(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc oviewers(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc params2list(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc pick(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc prob(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc rand(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc rand_seed(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc range(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ref(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc regex_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc replacetext(donk::proc_ctxt_t& ctxt,
                               donk::proc_args_t& args);
donk::running_proc replacetextEx(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc replacetextEx_char(donk::proc_ctxt_t& ctxt,
                                      donk::proc_args_t& args);
donk::running_proc replacetext_char(donk::proc_ctxt_t& ctxt,
                                    donk::proc_args_t& args);
donk::running_proc rgb(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc rgb2num(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc roll(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc round(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc run(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sha1(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc shell(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc shutdown(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sin(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sleep(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sorttext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sorttextEx(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc sound_(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc spantext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc spantext_char(donk::proc_ctxt_t& ctxt,
                                 donk::proc_args_t& args);
donk::running_proc splicetext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc splicetext_char(donk::proc_ctxt_t& ctxt,
                                   donk::proc_args_t& args);
donk::running_proc splittext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc splittext_char(donk::proc_ctxt_t& ctxt,
                                  donk::proc_args_t& args);
donk::running_proc sqrt(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc startup(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc stat(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc statpanel(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc step(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc step_away(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc step_rand(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc step_to(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc step_towards(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc tan(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc text(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc text2ascii(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc text2ascii_char(donk::proc_ctxt_t& ctxt,
                                   donk::proc_args_t& args);
donk::running_proc text2file(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc text2num(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc text2path(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc time2text(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc turn(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc typesof(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc uppertext(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc url_decode(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc url_encode(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc view(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc viewers(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc walk(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc walk_away(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc walk_rand(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc walk_to(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc walk_towards(donk::proc_ctxt_t& ctxt,
                                donk::proc_args_t& args);
donk::running_proc winclone(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc winexists(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc winget(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc winset(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc winshow(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
void Register(donk::iota_t& iota);

}  // namespace donk::api

#endif  // __DONK_API_ROOT_H__
