// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_definition_cc.tmpl
// Filename:    savefile.cc
#include "donk/api/savefile.h"

#include "donk/core/iota.h"
#include "donk/core/path.h"
#include "donk/core/procs.h"

namespace donk::api::savefile {
savefile_coretype::savefile_coretype(donk::path_t path) : donk::iota_t(path) {
  InternalCoreRegister();
}

donk::running_proc Del(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/Del");
}

donk::running_proc ExportText(donk::proc_ctxt_t& ctxt,
                              donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/ExportText");
}

donk::running_proc Flush(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/Flush");
}

donk::running_proc ImportText(donk::proc_ctxt_t& ctxt,
                              donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/ImportText");
}

donk::running_proc Lock(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/Lock");
}

donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/New");
}

donk::running_proc Unlock(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args) {
  co_yield ctxt.Unimplemented("/savefile/proc/Unlock");
}

void savefile_coretype::InternalCoreRegister() {
  RegisterProc("Del", donk::api::savefile::Del);
  RegisterProc("ExportText", donk::api::savefile::ExportText);
  RegisterProc("Flush", donk::api::savefile::Flush);
  RegisterProc("ImportText", donk::api::savefile::ImportText);
  RegisterProc("Lock", donk::api::savefile::Lock);
  RegisterProc("New", donk::api::savefile::New);
  RegisterProc("Unlock", donk::api::savefile::Unlock);
  RegisterVar("cd");
  RegisterVar("dir");
  RegisterVar("eof");
  RegisterVar("name");
  RegisterVar("parent_type");
  RegisterVar("tag");
  RegisterVar("type");
}

}  // namespace donk::api::savefile