// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    savefile.h

#ifndef __DONK_API_SAVEFILE_H__
#define __DONK_API_SAVEFILE_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::savefile {

class savefile_coretype : public virtual donk::iota_t {
 public:
  ~savefile_coretype() {}
  void InternalCoreRegister() override;

  savefile_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc Del(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ExportText(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Flush(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc ImportText(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Lock(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);
donk::running_proc Unlock(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::savefile

#endif  // __DONK_API_SAVEFILE_H__
