// Generated by Donk Transpiler. Changes may be overwritten.
// Template:    transformer_declaration.h.tmpl
// Filename:    sound.h

#ifndef __DONK_API_SOUND_H__
#define __DONK_API_SOUND_H__

#include "cppcoro/generator.hpp"
#include "donk/core/iota.h"
#include "donk/core/procs.h"

namespace donk::api::sound {

class sound_coretype : public virtual donk::iota_t {
 public:
  ~sound_coretype() {}
  void InternalCoreRegister() override;

  sound_coretype(donk::path_t path);

  friend class donk::iota_t;
};

donk::running_proc New(donk::proc_ctxt_t& ctxt, donk::proc_args_t& args);

}  // namespace donk::api::sound

#endif  // __DONK_API_SOUND_H__
